version: '3.8'

services:
  server:
    image: part6:new
    build: Dockerfile2
    container_name: cormac_server
  client:
    image: nginx
    container_name: cormac_client
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - server
